name: Build and Deploy
on:
  push:
    branches:
      - 'master'
permissions: write-all

jobs:
  build:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        shell: bash
        run: |
          make
          docker build . --tag ghcr.io/craftmaster2190/colton-party:latest --quiet

      - name: Publish
        shell: bash
        run: |
          docker push ghcr.io/craftmaster2190/colton-party:latest --quiet

      - name: Deploy
        shell: bash
        run: |
          curl -sS '${{secrets.DEPLOY_HOOK}}'
